# Generated by Django 2.2 on 2023-09-24 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qualification', models.CharField(max_length=500)),
                ('Morning_Time', models.CharField(default='NA', max_length=500)),
                ('Evening_Time', models.CharField(default='NA', max_length=500)),
                ('Phone_No', models.BigIntegerField()),
                ('Doctor_Fees', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage_Fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HomePage_fields', models.CharField(default='NA', max_length=200)),
                ('role', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=0)),
                ('state', models.CharField(default='ReceptionDashboard.Receptionist', max_length=500)),
                ('icon', models.CharField(default='fa fa-user', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Appointment_date', models.CharField(max_length=500)),
                ('Appointment_slot', models.CharField(max_length=500)),
                ('Approval_status', models.BooleanField(null=True)),
                ('Visit_dateTime', models.DateTimeField(null=True)),
                ('Patient_Medical_history', models.CharField(max_length=500)),
                ('Appointment_rejection_reason', models.CharField(default='NA', max_length=500)),
                ('Doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.Doctor_Details')),
                ('Patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_Gender', models.CharField(max_length=200)),
                ('Patient_Age', models.FloatField()),
                ('Patient_Address', models.CharField(max_length=500)),
                ('Patient_Weight', models.FloatField(default='0.00')),
                ('Patient_Contact', models.BigIntegerField(default='0')),
                ('Patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(max_length=200)),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NewAppointment_dateTime', models.DateTimeField(auto_now=True, null=True)),
                ('Doctor_Approval', models.BooleanField(default=False)),
                ('Receptionist_Approval', models.BooleanField(default=False)),
                ('Patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('Patient_Appointments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.Patient_Appointments')),
                ('Patient_Details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.Patient_Details')),
            ],
        ),
        migrations.CreateModel(
            name='Patients_Prescriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_of_Prescription', models.DateTimeField(auto_now=True, null=True)),
                ('Diagnosis', models.CharField(default='NA', max_length=500)),
                ('Medications', models.CharField(default='NA', max_length=500)),
                ('Dosage', models.CharField(default='NA', max_length=500)),
                ('Instructions', models.CharField(default='NA', max_length=500)),
                ('Doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor', to=settings.AUTH_USER_MODEL)),
                ('Patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Payment_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_date', models.DateTimeField(auto_now=True, null=True)),
                ('Amount', models.IntegerField()),
                ('Balance', models.IntegerField(default=0)),
                ('Patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='patient_appointments',
            name='Patient_Details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.Patient_Details'),
        ),
        migrations.AddField(
            model_name='doctor_details',
            name='Department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.DoctorDepartment'),
        ),
        migrations.AddField(
            model_name='doctor_details',
            name='Doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Doctor_Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_dateTime', models.DateTimeField(auto_now=True, null=True)),
                ('update_dateTime', models.DateTimeField(auto_now=True, null=True)),
                ('Doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
