# Generated by Django 2.2 on 2023-09-29 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_receptionist_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_payment_history',
            name='Patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.Doctor_Details'),
        ),
    ]
