# Generated by Django 2.2 on 2023-09-29 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20230929_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_payment_history',
            name='Patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
