# Generated by Django 2.2 on 2023-09-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20230929_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionist',
            name='Doctor_Approval',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
