# Generated by Django 2.2 on 2023-09-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_auto_20230929_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionist',
            name='Receptionist_Approval',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
