# Generated by Django 2.2 on 2023-09-30 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_auto_20230929_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_payment_history',
            name='Doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.Doctor_Details'),
        ),
    ]
