# Generated by Django 2.2 on 2023-11-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_architect_architect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_details',
            name='Doctor_Fees',
            field=models.IntegerField(null=True),
        ),
    ]
