# Generated by Django 2.2 on 2023-11-30 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_auto_20231129_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage_fields',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
