# Generated by Django 2.2 on 2023-11-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_homepage_fields_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_details',
            name='Doctor_Address',
            field=models.CharField(default='NA', max_length=500),
        ),
    ]
